# Generated by Django 3.2.7 on 2022-03-11 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220311_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accepted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('applicant_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='user.group')),
                ('receiver_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='user.group')),
            ],
        ),
    ]
